package rs.ac.bg.fon.ai.nprog.OrdinacijaKlijent.form.planIshrane;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Forma koja umogucuje nutricionisti da unese nove planove ishrana za pacijente
 * 
 * @author Iva Stanisic
 */
public class FrmKreirajPlanIshrane extends javax.swing.JFrame {

	/**
	 * Kreira novu instancu klase FrmKreirajPlanIshrane
	 * 
	 */
	public FrmKreirajPlanIshrane() {
		initComponents();
		setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblJela = new javax.swing.JLabel();
		cbTipJela = new javax.swing.JComboBox<>();
		lblKuvar = new javax.swing.JLabel();
		cbKuvar = new javax.swing.JComboBox<>();
		btnAdd = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblJela = new javax.swing.JTable();
		lbCount = new javax.swing.JLabel();
		spiner = new javax.swing.JSpinner();
		btnSearch = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblStavke = new javax.swing.JTable();
		btnDelete = new javax.swing.JButton();
		pnlPI = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		btnIzaberi = new javax.swing.JButton();
		lblDate = new javax.swing.JLabel();
		txtDate = new javax.swing.JTextField();
		txtDay = new javax.swing.JTextField();
		lblDay = new javax.swing.JLabel();
		lblAdmin = new javax.swing.JPanel();
		lblImeNutricioniste = new javax.swing.JLabel();
		txtImeNutricioniste = new javax.swing.JTextField();
		lblPrezimeNutricioniste = new javax.swing.JLabel();
		txtPrezimeNutricioniste = new javax.swing.JTextField();
		pnlPatient = new javax.swing.JPanel();
		lblImePacijenta = new javax.swing.JLabel();
		txtImePacijenta = new javax.swing.JTextField();
		txtPrezimePacijenta = new javax.swing.JTextField();
		lblPrezimePacijenta = new javax.swing.JLabel();
		btnKreirajPlan = new javax.swing.JButton();
		btnPromeniDatum = new javax.swing.JButton();
		cmbPacijenti = new javax.swing.JComboBox<>();
		btnFresh = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Plan ishrane");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Jela u ponudi:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12),
				new java.awt.Color(51, 0, 255))); // NOI18N

		lblJela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblJela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblJela.setText("Tip jela:");

		cbTipJela.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblKuvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblKuvar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblKuvar.setText("Kuvar:");

		cbKuvar.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnAdd.setText(" Dodaj");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		tblJela.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblJela);

		lbCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lbCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lbCount.setText("Količina:");

		btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnSearch.setText(" Pretraži");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});

		tblStavke
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(tblStavke);

		btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDelete.setText("Obriši");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});

		pnlPI.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Plan ishrane:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12),
				new java.awt.Color(51, 0, 255))); // NOI18N

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("Pacijent:");

		btnIzaberi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		btnIzaberi.setText("Izaberi pacijenta");
		btnIzaberi.setBorder(null);
		btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIzaberiActionPerformed(evt);
			}
		});

		lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblDate.setText("Datum:");

		txtDate.setText(" ");
		txtDate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtDateActionPerformed(evt);
			}
		});

		txtDay.setText(" ");

		lblDay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblDay.setText("Broj dana:");

		lblAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Nutricionista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

		lblImeNutricioniste.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblImeNutricioniste.setText("Ime:");

		txtImeNutricioniste.setText(" ");

		lblPrezimeNutricioniste.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblPrezimeNutricioniste.setText("Prezime:");

		txtPrezimeNutricioniste.setText(" ");

		javax.swing.GroupLayout lblAdminLayout = new javax.swing.GroupLayout(lblAdmin);
		lblAdmin.setLayout(lblAdminLayout);
		lblAdminLayout.setHorizontalGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(lblAdminLayout.createSequentialGroup().addGap(36, 36, 36)
						.addGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(lblAdminLayout.createSequentialGroup()
										.addComponent(lblImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(txtImeNutricioniste,
												javax.swing.GroupLayout.PREFERRED_SIZE, 238,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(lblAdminLayout.createSequentialGroup()
										.addComponent(lblPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE,
												50, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(txtPrezimeNutricioniste,
												javax.swing.GroupLayout.PREFERRED_SIZE, 238,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(75, Short.MAX_VALUE)));
		lblAdminLayout.setVerticalGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(lblAdminLayout.createSequentialGroup().addContainerGap()
						.addGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(28, Short.MAX_VALUE)));

		pnlPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Pacijent:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

		lblImePacijenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblImePacijenta.setText("Ime");

		txtImePacijenta.setText(" ");

		txtPrezimePacijenta.setText(" ");

		lblPrezimePacijenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblPrezimePacijenta.setText("Prezime");

		javax.swing.GroupLayout pnlPatientLayout = new javax.swing.GroupLayout(pnlPatient);
		pnlPatient.setLayout(pnlPatientLayout);
		pnlPatientLayout.setHorizontalGroup(pnlPatientLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPatientLayout.createSequentialGroup().addGap(37, 37, 37)
						.addGroup(pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlPatientLayout.createSequentialGroup()
										.addComponent(lblImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(txtImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 238,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlPatientLayout.createSequentialGroup()
										.addComponent(lblPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
												Short.MAX_VALUE)
										.addComponent(txtPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 238,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(37, 37, 37)));
		pnlPatientLayout.setVerticalGroup(pnlPatientLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPatientLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblImePacijenta).addComponent(txtImePacijenta,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblPrezimePacijenta).addComponent(txtPrezimePacijenta,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(42, Short.MAX_VALUE)));

		btnKreirajPlan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnKreirajPlan.setForeground(new java.awt.Color(255, 0, 51));
		btnKreirajPlan.setText("Kreiraj plan ishrane");
		btnKreirajPlan.setBorder(null);
		btnKreirajPlan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKreirajPlanActionPerformed(evt);
			}
		});

		btnPromeniDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnPromeniDatum.setForeground(new java.awt.Color(51, 0, 255));
		btnPromeniDatum.setText("Promenite datum");

		cmbPacijenti.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout pnlPILayout = new javax.swing.GroupLayout(pnlPI);
		pnlPI.setLayout(pnlPILayout);
		pnlPILayout.setHorizontalGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPILayout.createSequentialGroup().addGap(20, 20, 20).addGroup(pnlPILayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlPILayout.createSequentialGroup()
								.addComponent(btnKreirajPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 659,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
								.addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlPILayout.createSequentialGroup().addGroup(pnlPILayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 61,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlPILayout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(pnlPILayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnPromeniDatum,
																javax.swing.GroupLayout.PREFERRED_SIZE, 147,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(pnlPILayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		false)
																.addComponent(txtDate,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(btnIzaberi,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 343,
																		Short.MAX_VALUE))))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												pnlPILayout.createSequentialGroup().addGap(6, 6, 6).addComponent(txtDay,
														javax.swing.GroupLayout.PREFERRED_SIZE, 343,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 352,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pnlPatient, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()))));
		pnlPILayout.setVerticalGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPILayout.createSequentialGroup().addGroup(pnlPILayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlPILayout.createSequentialGroup().addGap(34, 34, 34)
								.addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnPromeniDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnKreirajPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlPILayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pnlPatient, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(169, 169, 169)));

		btnFresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnFresh.setText("Osveži");
		btnFresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnFreshActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(26, 26, 26)
										.addComponent(lblJela, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbTipJela, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(lblKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnFresh, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(
												btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 144,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
										.addComponent(jScrollPane2))
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addComponent(pnlPI,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(15, 15, 15)
										.addComponent(lbCount, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
										.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblJela, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cbTipJela, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cbKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnFresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(29, 29, 29)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(22, 22, 22)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lbCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(pnlPI,
								javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(44, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(20, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnKreirajPlanActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnFreshActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	/*
	 * /**
	 * 
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	/**
	 * Referenca na JButton objekat koji predstavlja dugme za dodavanje.
	 */
	private javax.swing.JButton btnAdd;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za brisanje.
	 */
	private javax.swing.JButton btnDelete;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za osvežavanje.
	 */
	private javax.swing.JButton btnFresh;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za izbor.
	 */
	private javax.swing.JButton btnIzaberi;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za kreiranje plana.
	 */
	private javax.swing.JButton btnKreirajPlan;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za promenu datuma.
	 */
	private javax.swing.JButton btnPromeniDatum;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za pretragu.
	 */
	private javax.swing.JButton btnSearch;

	/**
	 * Referenca na JComboBox objekat koji predstavlja izbor kuvara.
	 */
	private javax.swing.JComboBox<Object> cbKuvar;

	/**
	 * Referenca na JComboBox objekat koji predstavlja izbor tipa jela.
	 */
	private javax.swing.JComboBox<Object> cbTipJela;

	/**
	 * Referenca na JComboBox objekat koji predstavlja izbor pacijenata.
	 */
	private javax.swing.JComboBox<Object> cmbPacijenti;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku "jLabel1".
	 */
	private javax.swing.JLabel jLabel1;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel 1.
	 */
	private javax.swing.JPanel jPanel1;

	/**
	 * Referenca na JScrollPane objekat koji predstavlja okvir za tabelu 1.
	 */
	private javax.swing.JScrollPane jScrollPane1;

	/**
	 * Referenca na JScrollPane objekat koji predstavlja okvir za tabelu 2.
	 */
	private javax.swing.JScrollPane jScrollPane2;

	/**
	 * Referenca na JLabel objekat koji predstavlja brojač.
	 */
	private javax.swing.JLabel lbCount;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel za administratora.
	 */
	private javax.swing.JPanel lblAdmin;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za datum.
	 */
	private javax.swing.JLabel lblDate;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za dan.
	 */
	private javax.swing.JLabel lblDay;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za ime nutricioniste.
	 */
	private javax.swing.JLabel lblImeNutricioniste;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za ime pacijenta.
	 */
	private javax.swing.JLabel lblImePacijenta;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za jela.
	 */
	private javax.swing.JLabel lblJela;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za kuvara.
	 */
	private javax.swing.JLabel lblKuvar;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za prezime nutricioniste.
	 */
	private javax.swing.JLabel lblPrezimeNutricioniste;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za prezime pacijenta.
	 */
	private javax.swing.JLabel lblPrezimePacijenta;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel za plan ishrane.
	 */
	private javax.swing.JPanel pnlPI;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel za pacijenta.
	 */
	private javax.swing.JPanel pnlPatient;

	/**
	 * Referenca na JSpinner objekat koji predstavlja spinner.
	 */
	private javax.swing.JSpinner spiner;

	/**
	 * Referenca na JTable objekat koji predstavlja tabelu jela.
	 */
	private javax.swing.JTable tblJela;

	/**
	 * Referenca na JTable objekat koji predstavlja tabelu stavki.
	 */
	private javax.swing.JTable tblStavke;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za datum.
	 */
	private javax.swing.JTextField txtDate;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za dan.
	 */
	private javax.swing.JTextField txtDay;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za ime
	 * nutricioniste.
	 */
	private javax.swing.JTextField txtImeNutricioniste;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za ime
	 * pacijenta.
	 */
	private javax.swing.JTextField txtImePacijenta;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za prezime
	 * nutricioniste.
	 */
	private javax.swing.JTextField txtPrezimeNutricioniste;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za prezime
	 * pacijenta.
	 */
	private javax.swing.JTextField txtPrezimePacijenta;

	// End of variables declaration
	/**
	 * Vraca JButton btnAdd
	 *
	 * @return JButton btnAdd
	 */
	public JButton getBtnAdd() {
		return btnAdd;
	}

	/**
	 * Vraca JButton btnIzaberi
	 *
	 * @return JButton btnIzaberi
	 */
	public JButton getBtnAdd1() {
		return btnIzaberi;
	}

	/**
	 * Vraca JButton btnDelete
	 *
	 * @return JButton btnDelete
	 */
	public JButton getBtnDelete() {
		return btnDelete;
	}

	/**
	 * Vraca JButton btnKreirajPlan
	 *
	 * @return JButton btnKreirajPlan
	 */
	public JButton getBtnDelete1() {
		return btnKreirajPlan;
	}

	/**
	 * Vraca JButton btnFresh
	 *
	 * @return JButton btnFresh
	 */
	public JButton getBtnFresh() {
		return btnFresh;
	}

	/**
	 * Vraca JButton btnSearch
	 *
	 * @return JButton btnSearch
	 */
	public JButton getBtnSearch() {
		return btnSearch;
	}

	/**
	 * Vraca JComboBox cbKuvar
	 *
	 * @return JComboBox cbKuvar
	 */
	public JComboBox<Object> getCbKuvar() {
		return cbKuvar;
	}

	/**
	 * Vraca JComboBox cbTipJela
	 *
	 * @return JComboBox cbTipJela
	 */
	public JComboBox<Object> getCbTipJela() {
		return cbTipJela;
	}

	/**
	 * Vraca JLabel jLabel1
	 *
	 * @return JLabel jLabel1
	 */
	public JLabel getjLabel1() {
		return jLabel1;
	}

	/**
	 * Vraca JPanel jPanel1
	 *
	 * @return JPanel jPanel1
	 */
	public JPanel getjPanel1() {
		return jPanel1;
	}

	/**
	 * Vraca JScrollPane jScrollPane1
	 *
	 * @return JScrollPane jScrollPane1
	 */
	public JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	/**
	 * Vraca JScrollPane jScrollPane2
	 *
	 * @return JScrollPane jScrollPane2
	 */
	public JScrollPane getjScrollPane2() {
		return jScrollPane2;
	}

	/**
	 * Vraca JLabel lbCount
	 *
	 * @return JLabel lbCount
	 */
	public JLabel getLbCount() {
		return lbCount;
	}

	/**
	 * Vraca JLabel lblAdmin
	 *
	 * @return JLabel lblAdmin
	 */
	public JPanel getLblAdmin() {
		return lblAdmin;
	}

	/**
	 * Vraca JLabel lblDate
	 *
	 * @return JLabel lblDate
	 */
	public JLabel getLblDate() {
		return lblDate;
	}

	/**
	 * Vraca JLabel lblDay
	 *
	 * @return JLabel lblDay
	 */
	public JLabel getLblDay() {
		return lblDay;
	}

	/**
	 * Vraca JLabel lblImeNutricioniste
	 *
	 * @return JLabel lblImeNutricioniste
	 */
	public JLabel getLblImeNutricioniste() {
		return lblImeNutricioniste;
	}

	/**
	 * Vraca JLabel lblImePacijenta
	 *
	 * @return JLabel lblImePacijenta
	 */
	public JLabel getLblImePacijenta() {
		return lblImePacijenta;
	}

	/**
	 * Vraca JLabel lblJela
	 *
	 * @return JLabel lblJela
	 */
	public JLabel getLblJela() {
		return lblJela;
	}

	/**
	 * Vraca JLabel lblKuvar
	 *
	 * @return JLabel lblKuvar
	 */
	public JLabel getLblKuvar() {
		return lblKuvar;
	}

	/**
	 * Vraca JLabel lblPrezimeNutricioniste
	 *
	 * @return JLabel lblPrezimeNutricioniste
	 */
	public JLabel getLblPrezimeNutricioniste() {
		return lblPrezimeNutricioniste;
	}

	/**
	 * Vraca JLabel lblPrezimePacijenta
	 *
	 * @return JLabel lblPrezimePacijenta
	 */
	public JLabel getLblPrezimePacijenta() {
		return lblPrezimePacijenta;
	}

	/**
	 * Vraca JPanel pnlPI
	 *
	 * @return JPanel pnlPI
	 */
	public JPanel getPnlPI() {
		return pnlPI;
	}

	/**
	 * Vraca JPanel pnlPatient
	 *
	 * @return JPanel pnlPatient
	 */
	public JPanel getPnlPatient() {
		return pnlPatient;
	}

	/**
	 * Vraca JSpinner spiner
	 *
	 * @return JSpinner spiner
	 */
	public JSpinner getSpiner() {
		return spiner;
	}

	/**
	 * Vraca JTable tblJela za prikaz jela na sistemu
	 *
	 * @return JTable tblJela
	 */
	public JTable getTblJela() {
		return tblJela;
	}

	/**
	 * Vraca JTable tblStavke za prikaz stavki plana ishrane
	 *
	 * @return JTable tblStavke
	 */
	public JTable getTblStavke() {
		return tblStavke;
	}

	/**
	 * Vraca JTextField txtDate za prikaz stavki plana ishrane
	 *
	 * @return JTextField txtDate
	 */
	public JTextField getTxtDate() {
		return txtDate;
	}

	/**
	 * Vraca JTextField txtDay za unos broja trajanja plana ishrane
	 *
	 * @return JTextField txtDay
	 */
	public JTextField getTxtDay() {
		return txtDay;
	}

	/**
	 * Vraca JTextField txtImeNutricioniste za unos imena nutricioniste koji vodi
	 * plana ishrane
	 *
	 * @return JTextField txtImeNutricioniste
	 */
	public JTextField getTxtImeNutricioniste() {
		return txtImeNutricioniste;
	}

	/**
	 * Vraca JTextField txtImePacijenta za unos imena pacijenta za kojeg se kreira
	 * plana ishrane
	 *
	 * @return JTextField txtImePacijenta
	 */
	public JTextField getTxtImePacijenta() {
		return txtImePacijenta;
	}

	/**
	 * Vraca JTextField txtPrezimeNutricioniste za unos prezimena nutricioniste koji
	 * vodi plana ishrane
	 *
	 * @return JTextField txtPrezimeNutricioniste
	 */
	public JTextField getTxtPrezimeNutricioniste() {
		return txtPrezimeNutricioniste;
	}

	/**
	 * Vraca JTextField txtImePacijenta za unos prezimena pacijenta za kojeg se
	 * kreira plana ishrane
	 *
	 * @return JTextField txtImePacijenta
	 */
	public JTextField getTxtPrezimePacijenta() {
		return txtPrezimePacijenta;
	}

	/**
	 * Postavlja JButton btnAdd
	 *
	 * @param btnAdd JButton dugme za dodavanje jela u stavku plana
	 */
	public void setBtnAdd(JButton btnAdd) {
		this.btnAdd = btnAdd;
	}

	/**
	 * Postavlja JButton btnIzaberi
	 *
	 * @param btnAdd1 JButton dugme za dodavanje stavki plana
	 */
	public void setBtnAdd1(JButton btnAdd1) {
		this.btnIzaberi = btnAdd1;
	}

	/**
	 * Postavlja JButton btnDelete
	 *
	 * @param btnDelete JButton dugme za brisanje jela na stavki plana
	 */
	public void setBtnDelete(JButton btnDelete) {
		this.btnDelete = btnDelete;
	}

	/**
	 * Postavlja JButton btnKreirajPlan
	 *
	 * @param btnDelete1 JButton dugme za kreiranje plana
	 */
	public void setBtnDelete1(JButton btnDelete1) {
		this.btnKreirajPlan = btnDelete1;
	}

	/**
	 * Postavlja JButton btnFresh
	 *
	 * @param btnFresh JButton dugme za osvezavanje panela sa jelima
	 */
	public void setBtnFresh(JButton btnFresh) {
		this.btnFresh = btnFresh;
	}

	/**
	 * Postavlja JButton btnSearch
	 *
	 * @param btnSearch JButton dugme za pretragu
	 */
	public void setBtnSearch(JButton btnSearch) {
		this.btnSearch = btnSearch;
	}

	/**
	 * Postavlja JComboBox komponentu za kuvare koja se koristi u formi
	 *
	 * @param cbKuvar JComboBox komponenta za kuvare
	 */
	public void setCbKuvar(JComboBox<Object> cbKuvar) {
		this.cbKuvar = cbKuvar;
	}

	/**
	 * Postavlja JComboBox komponentu za tipove jela koja se koristi u formi
	 *
	 * @param cbTipJela JComboBox komponenta za tipove jela
	 */
	public void setCbTipJela(JComboBox<Object> cbTipJela) {
		this.cbTipJela = cbTipJela;
	}

	/**
	 * Postavlja JLabel JLabel
	 * 
	 * @param JLabel labela koja se postavlja
	 */
	public void setjLabel1(JLabel JLabel) {
		this.jLabel1 = jLabel1;
	}

	/**
	 * Postavlja JPanel jPanel1
	 * 
	 * @param jPanel1 panel koja se postavlja
	 */
	public void setjPanel1(JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	/**
	 * Postavlja JScrollPane jScrollPane1
	 * 
	 * @param jScrollPane1 scrollpanel koja se postavlja
	 */
	public void setjScrollPane1(JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	/**
	 * Postavlja JScrollPane jScrollPane2
	 * 
	 * @param jScrollPane2 scrollpanel koja se postavlja
	 */
	public void setjScrollPane2(JScrollPane jScrollPane2) {
		this.jScrollPane2 = jScrollPane2;
	}

	/**
	 * Postavlja JLabel lbCount
	 * 
	 * @param lbCount labela koja se postavlja
	 */
	public void setLbCount(JLabel lbCount) {
		this.lbCount = lbCount;
	}

	/**
	 * Postavlja JLabel lblAdmin
	 * 
	 * @param lblAdmin labela koja se postavlja
	 */
	public void setLblAdmin(JPanel lblAdmin) {
		this.lblAdmin = lblAdmin;
	}

	/**
	 * Postavlja JLabel lblDate
	 * 
	 * @param lblDate labela koja se postavlja
	 */
	public void setLblDate(JLabel lblDate) {
		this.lblDate = lblDate;
	}

	/**
	 * Postavlja JLabel lblDay
	 * 
	 * @param lblDay labela koja se postavlja
	 */
	public void setLblDay(JLabel lblDay) {
		this.lblDay = lblDay;
	}

	/**
	 * Postavlja JLabel lblImeNutricioniste
	 * 
	 * @param lblImeNutricioniste labela koja se postavlja
	 */
	public void setLblImeNutricioniste(JLabel lblImeNutricioniste) {
		this.lblImeNutricioniste = lblImeNutricioniste;
	}

	/**
	 * Postavlja JLabel lblImePacijenta
	 * 
	 * @param lblImePacijenta labela koja se postavlja
	 */
	public void setLblImePacijenta(JLabel lblImePacijenta) {
		this.lblImePacijenta = lblImePacijenta;
	}

	/**
	 * Postavlja JLabel lblJela
	 * 
	 * @param lblJela labela koja se postavlja
	 */
	public void setLblJela(JLabel lblJela) {
		this.lblJela = lblJela;
	}

	/**
	 * Postavlja JLabel lblKuvar
	 * 
	 * @param lblKuvar labela koja se postavlja
	 */
	public void setLblKuvar(JLabel lblKuvar) {
		this.lblKuvar = lblKuvar;
	}

	/**
	 * Postavlja JLabel lblPrezimeNutricioniste
	 * 
	 * @param lblPrezimeNutricioniste labela koja se postavlja
	 */
	public void setLblPrezimeNutricioniste(JLabel lblPrezimeNutricioniste) {
		this.lblPrezimeNutricioniste = lblPrezimeNutricioniste;
	}

	/**
	 * Postavlja JLabel lblPrezimePacijenta
	 * 
	 * @param lblPrezimePacijenta labela koja se postavlja
	 */
	public void setLblPrezimePacijenta(JLabel lblPrezimePacijenta) {
		this.lblPrezimePacijenta = lblPrezimePacijenta;
	}

	/**
	 * Postavlja JPanel pnlPI
	 * 
	 * @param pnlPI panel koji se postavlja
	 */
	public void setPnlPI(JPanel pnlPI) {
		this.pnlPI = pnlPI;
	}

	/**
	 * Postavlja JPanel pnlPatient za prikaz pacijenata
	 * 
	 * @param pnlPatient panel koji se postavlja
	 */
	public void setPnlPatient(JPanel pnlPatient) {
		this.pnlPatient = pnlPatient;
	}

	/**
	 * Postavlja JSpinner spiner
	 * 
	 * @param spiner spiner koji se postavlja
	 */
	public void setSpiner(JSpinner spiner) {
		this.spiner = spiner;
	}

	/**
	 * Postavlja JTable tblJela za prikaz jela
	 * 
	 * @param tblJela tabela koja se postavlja
	 */
	public void setTblJela(JTable tblJela) {
		this.tblJela = tblJela;
	}

	/**
	 * Postavlja JTable tblStavke za prikaz stavki plana ishrana
	 * 
	 * @param tblStavke tabela koja se postavlja
	 */
	public void setTblStavke(JTable tblStavke) {
		this.tblStavke = tblStavke;
	}

	/**
	 * Postavlja JTextField txtDate za prikaz datuma plana ishrana
	 * 
	 * @param txtDate polje koja se postavlja za datum plana
	 */
	public void setTxtDate(JTextField txtDate) {
		this.txtDate = txtDate;
	}

	/**
	 * Postavlja JTextField txtDay za prikaz broja dana plana ishrana
	 * 
	 * @param txtDay polje koja se postavlja za broj dana trajanja plana
	 */
	public void setTxtDay(JTextField txtDay) {
		this.txtDay = txtDay;
	}

	/**
	 * Postavlja JTextField txtImeNutricioniste za prikaz imena nutricioniste
	 * 
	 * @param txtImeNutricioniste polje koja se postavlja za prikaz imena
	 *                            nutricioniste
	 */
	public void setTxtImeNutricioniste(JTextField txtImeNutricioniste) {
		this.txtImeNutricioniste = txtImeNutricioniste;
	}

	/**
	 * Postavlja JTextField txtImePacijenta za prikaz imena pacijenta
	 * 
	 * @param txtImePacijenta polje koja se postavlja za prikaz imena pacijenta
	 */
	public void setTxtImePacijenta(JTextField txtImePacijenta) {
		this.txtImePacijenta = txtImePacijenta;
	}

	/**
	 * Postavlja JTextField txtPrezimeNutricioniste za prikaz prezimena
	 * nutricioniste
	 * 
	 * @param txtPrezimeNutricioniste polje koja se postavlja za prikaz prezimena
	 *                                nutricioniste
	 */
	public void setTxtPrezimeNutricioniste(JTextField txtPrezimeNutricioniste) {
		this.txtPrezimeNutricioniste = txtPrezimeNutricioniste;
	}

	/**
	 * Postavlja JTextField txtPrezimePacijenta za prikaz prezimena pacijenta
	 * 
	 * @param txtPrezimePacijenta polje koja se postavlja za prikaz prezimena
	 *                            pacijenta
	 */
	public void setTxtPrezimePacijenta(JTextField txtPrezimePacijenta) {
		this.txtPrezimePacijenta = txtPrezimePacijenta;
	}

	/**
	 * Vraca JComboBox sa pacijentima
	 * 
	 * @return cmbPacijenti combobox sa pacijentima
	 */
	public JComboBox<Object> getCmbPacijenti() {
		return cmbPacijenti;
	}

	/**
	 * Postavlja JComboBox cmbPacijenti za prikaz pacijenta
	 * 
	 * @param cmbPacijenti koja se postavlja za prikaz pacijenata
	 */
	public void setCmbPacijenti(JComboBox<Object> cmbPacijenti) {
		this.cmbPacijenti = cmbPacijenti;
	}

	/**
	 * Dodaje ActionListener na dugme btnAdd
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnAddActionListener(ActionListener actionListener) {
		btnAdd.addActionListener(actionListener);
	}

	/**
	 * Dodaje ActionListener na dugme btnSearch
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnSearchActionListener(ActionListener actionListener) {
		btnSearch.addActionListener(actionListener);
	}

	/**
	 * Dodaje ActionListener na dugme btnDelete
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnDeleteActionListener(ActionListener actionListener) {
		btnDelete.addActionListener(actionListener);
	}

	/**
	 * Dodaje ActionListener na dugme btnIzaberi
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnIzaberiActionListener(ActionListener actionListener) {
		btnIzaberi.addActionListener(actionListener);
	}

	/**
	 * Dodaje ActionListener na dugme btnKreirajPlan
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnKreirajPlansActionListener(ActionListener actionListener) {
		btnKreirajPlan.addActionListener(actionListener);
	}

	/**
	 * Dodaje ActionListener na dugme btnFresh
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnFreshPlansActionListener(ActionListener actionListener) {
		btnFresh.addActionListener(actionListener);
	}

	/**
	 * Dodaje ActionListener na dugme btnPromeniDatum
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnPromeniDatumActionListener(ActionListener actionListener) {
		btnPromeniDatum.addActionListener(actionListener);
	}
}
