package rs.ac.bg.fon.ai.nprog.OrdinacijaKlijent.form.planIshrane;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Iva
 */
public class FrmKreirajPlanIshrane extends javax.swing.JFrame {

    /**
     * Creates new form FrmKreirajPlanIshrane
     */
    public FrmKreirajPlanIshrane() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJela = new javax.swing.JLabel();
        cbTipJela = new javax.swing.JComboBox<>();
        lblKuvar = new javax.swing.JLabel();
        cbKuvar = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJela = new javax.swing.JTable();
        lbCount = new javax.swing.JLabel();
        spiner = new javax.swing.JSpinner();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        pnlPI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIzaberi = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        lblDay = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JPanel();
        lblImeNutricioniste = new javax.swing.JLabel();
        txtImeNutricioniste = new javax.swing.JTextField();
        lblPrezimeNutricioniste = new javax.swing.JLabel();
        txtPrezimeNutricioniste = new javax.swing.JTextField();
        pnlPatient = new javax.swing.JPanel();
        lblImePacijenta = new javax.swing.JLabel();
        txtImePacijenta = new javax.swing.JTextField();
        txtPrezimePacijenta = new javax.swing.JTextField();
        lblPrezimePacijenta = new javax.swing.JLabel();
        btnKreirajPlan = new javax.swing.JButton();
        btnPromeniDatum = new javax.swing.JButton();
        cmbPacijenti = new javax.swing.JComboBox<>();
        btnFresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plan ishrane");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null), "Jela u ponudi:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12), new java.awt.Color(51, 0, 255))); // NOI18N

        lblJela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJela.setText("Tip jela:");

        cbTipJela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblKuvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKuvar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKuvar.setText("Kuvar:");

        cbKuvar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText(" Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblJela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJela);

        lbCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCount.setText("Količina:");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText(" Pretraži");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        pnlPI.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null), "Plan ishrane:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pacijent:");

        btnIzaberi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIzaberi.setText("Izaberi pacijenta");
        btnIzaberi.setBorder(null);
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setText("Datum:");

        txtDate.setText(" ");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtDay.setText(" ");

        lblDay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDay.setText("Broj dana:");

        lblAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null), "Nutricionista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        lblImeNutricioniste.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblImeNutricioniste.setText("Ime:");

        txtImeNutricioniste.setText(" ");

        lblPrezimeNutricioniste.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrezimeNutricioniste.setText("Prezime:");

        txtPrezimeNutricioniste.setText(" ");

        javax.swing.GroupLayout lblAdminLayout = new javax.swing.GroupLayout(lblAdmin);
        lblAdmin.setLayout(lblAdminLayout);
        lblAdminLayout.setHorizontalGroup(
            lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblAdminLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblAdminLayout.createSequentialGroup()
                        .addComponent(lblImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblAdminLayout.createSequentialGroup()
                        .addComponent(lblPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        lblAdminLayout.setVerticalGroup(
            lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezimeNutricioniste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null), "Pacijent:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        lblImePacijenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblImePacijenta.setText("Ime");

        txtImePacijenta.setText(" ");

        txtPrezimePacijenta.setText(" ");

        lblPrezimePacijenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrezimePacijenta.setText("Prezime");

        javax.swing.GroupLayout pnlPatientLayout = new javax.swing.GroupLayout(pnlPatient);
        pnlPatient.setLayout(pnlPatientLayout);
        pnlPatientLayout.setHorizontalGroup(
            pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientLayout.createSequentialGroup()
                        .addComponent(lblImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPatientLayout.createSequentialGroup()
                        .addComponent(lblPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(txtPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        pnlPatientLayout.setVerticalGroup(
            pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImePacijenta)
                    .addComponent(txtImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezimePacijenta)
                    .addComponent(txtPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnKreirajPlan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKreirajPlan.setForeground(new java.awt.Color(255, 0, 51));
        btnKreirajPlan.setText("Kreiraj plan ishrane");
        btnKreirajPlan.setBorder(null);
        btnKreirajPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPlanActionPerformed(evt);
            }
        });

        btnPromeniDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPromeniDatum.setForeground(new java.awt.Color(51, 0, 255));
        btnPromeniDatum.setText("Promenite datum");

        cmbPacijenti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlPILayout = new javax.swing.GroupLayout(pnlPI);
        pnlPI.setLayout(pnlPILayout);
        pnlPILayout.setHorizontalGroup(
            pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPILayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPILayout.createSequentialGroup()
                        .addComponent(btnKreirajPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPILayout.createSequentialGroup()
                        .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPILayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPromeniDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnIzaberi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPILayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlPILayout.setVerticalGroup(
            pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPILayout.createSequentialGroup()
                .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPILayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromeniDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreirajPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPILayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(169, 169, 169))
        );

        btnFresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFresh.setText("Osveži");
        btnFresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblJela, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipJela, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFresh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbCount, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJela, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipJela, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKuvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPI, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
    }                                      


    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
    }                                         

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
    }                                         

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void btnKreirajPlanActionPerformed(java.awt.event.ActionEvent evt) {                                               

    }                                              

    private void btnFreshActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }                                        

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFresh;
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnKreirajPlan;
    private javax.swing.JButton btnPromeniDatum;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Object

    > cbKuvar;
    private javax.swing.JComboBox<Object> cbTipJela;
    private javax.swing.JComboBox<Object> cmbPacijenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCount;
    private javax.swing.JPanel lblAdmin;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblImeNutricioniste;
    private javax.swing.JLabel lblImePacijenta;
    private javax.swing.JLabel lblJela;
    private javax.swing.JLabel lblKuvar;
    private javax.swing.JLabel lblPrezimeNutricioniste;
    private javax.swing.JLabel lblPrezimePacijenta;
    private javax.swing.JPanel pnlPI;
    private javax.swing.JPanel pnlPatient;
    private javax.swing.JSpinner spiner;
    private javax.swing.JTable tblJela;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtImeNutricioniste;
    private javax.swing.JTextField txtImePacijenta;
    private javax.swing.JTextField txtPrezimeNutricioniste;
    private javax.swing.JTextField txtPrezimePacijenta;
    // End of variables declaration                   

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JButton getBtnAdd1() {
        return btnIzaberi;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnDelete1() {
        return btnKreirajPlan;
    }

    public JButton getBtnFresh() {
        return btnFresh;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JComboBox<Object> getCbKuvar() {
        return cbKuvar;
    }

    public JComboBox<Object> getCbTipJela() {
        return cbTipJela;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JLabel getLbCount() {
        return lbCount;
    }

    public JPanel getLblAdmin() {
        return lblAdmin;
    }

    public JLabel getLblDate() {
        return lblDate;
    }

    public JLabel getLblDay() {
        return lblDay;
    }

    public JLabel getLblImeNutricioniste() {
        return lblImeNutricioniste;
    }

    public JLabel getLblImePacijenta() {
        return lblImePacijenta;
    }

    public JLabel getLblJela() {
        return lblJela;
    }

    public JLabel getLblKuvar() {
        return lblKuvar;
    }

    public JLabel getLblPrezimeNutricioniste() {
        return lblPrezimeNutricioniste;
    }

    public JLabel getLblPrezimePacijenta() {
        return lblPrezimePacijenta;
    }

    public JPanel getPnlPI() {
        return pnlPI;
    }

    public JPanel getPnlPatient() {
        return pnlPatient;
    }

    public JSpinner getSpiner() {
        return spiner;
    }

    public JTable getTblJela() {
        return tblJela;
    }

    public JTable getTblStavke() {
        return tblStavke;
    }

    public JTextField getTxtDate() {
        return txtDate;
    }

    public JTextField getTxtDay() {
        return txtDay;
    }

    public JTextField getTxtImeNutricioniste() {
        return txtImeNutricioniste;
    }

    public JTextField getTxtImePacijenta() {
        return txtImePacijenta;
    }

    public JTextField getTxtPrezimeNutricioniste() {
        return txtPrezimeNutricioniste;
    }

    public JTextField getTxtPrezimePacijenta() {
        return txtPrezimePacijenta;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public void setBtnAdd1(JButton btnAdd1) {
        this.btnIzaberi = btnAdd1;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public void setBtnDelete1(JButton btnDelete1) {
        this.btnKreirajPlan = btnDelete1;
    }

    public void setBtnFresh(JButton btnFresh) {
        this.btnFresh = btnFresh;
    }

    public void setBtnSearch(JButton btnSearch) {
        this.btnSearch = btnSearch;
    }

    public void setCbKuvar(JComboBox<Object> cbKuvar) {
        this.cbKuvar = cbKuvar;
    }

    public void setCbTipJela(JComboBox<Object> cbTipJela) {
        this.cbTipJela = cbTipJela;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public void setLbCount(JLabel lbCount) {
        this.lbCount = lbCount;
    }

    public void setLblAdmin(JPanel lblAdmin) {
        this.lblAdmin = lblAdmin;
    }

    public void setLblDate(JLabel lblDate) {
        this.lblDate = lblDate;
    }

    public void setLblDay(JLabel lblDay) {
        this.lblDay = lblDay;
    }

    public void setLblImeNutricioniste(JLabel lblImeNutricioniste) {
        this.lblImeNutricioniste = lblImeNutricioniste;
    }

    public void setLblImePacijenta(JLabel lblImePacijenta) {
        this.lblImePacijenta = lblImePacijenta;
    }

    public void setLblJela(JLabel lblJela) {
        this.lblJela = lblJela;
    }

    public void setLblKuvar(JLabel lblKuvar) {
        this.lblKuvar = lblKuvar;
    }

    public void setLblPrezimeNutricioniste(JLabel lblPrezimeNutricioniste) {
        this.lblPrezimeNutricioniste = lblPrezimeNutricioniste;
    }

    public void setLblPrezimePacijenta(JLabel lblPrezimePacijenta) {
        this.lblPrezimePacijenta = lblPrezimePacijenta;
    }

    public void setPnlPI(JPanel pnlPI) {
        this.pnlPI = pnlPI;
    }

    public void setPnlPatient(JPanel pnlPatient) {
        this.pnlPatient = pnlPatient;
    }

    public void setSpiner(JSpinner spiner) {
        this.spiner = spiner;
    }

    public void setTblJela(JTable tblJela) {
        this.tblJela = tblJela;
    }

    public void setTblStavke(JTable tblStavke) {
        this.tblStavke = tblStavke;
    }

    public void setTxtDate(JTextField txtDate) {
        this.txtDate = txtDate;
    }

    public void setTxtDay(JTextField txtDay) {
        this.txtDay = txtDay;
    }

    public void setTxtImeNutricioniste(JTextField txtImeNutricioniste) {
        this.txtImeNutricioniste = txtImeNutricioniste;
    }

    public void setTxtImePacijenta(JTextField txtImePacijenta) {
        this.txtImePacijenta = txtImePacijenta;
    }

    public void setTxtPrezimeNutricioniste(JTextField txtPrezimeNutricioniste) {
        this.txtPrezimeNutricioniste = txtPrezimeNutricioniste;
    }

    public void setTxtPrezimePacijenta(JTextField txtPrezimePacijenta) {
        this.txtPrezimePacijenta = txtPrezimePacijenta;
    }

    public JComboBox<Object> getCmbPacijenti() {
        return cmbPacijenti;
    }

    public void setCmbPacijenti(JComboBox<Object> cmbPacijenti) {
        this.cmbPacijenti = cmbPacijenti;
    }

    

    public void addbtnAddActionListener(ActionListener actionListener) {
        btnAdd.addActionListener(actionListener);
    }

    public void addbtnSearchActionListener(ActionListener actionListener) {
        btnSearch.addActionListener(actionListener);
    }

    public void addbtnDeleteActionListener(ActionListener actionListener) {
        btnDelete.addActionListener(actionListener);
    }

    public void addbtnIzaberiActionListener(ActionListener actionListener) {
        btnIzaberi.addActionListener(actionListener);
    }

    public void addbtnKreirajPlansActionListener(ActionListener actionListener) {
        btnKreirajPlan.addActionListener(actionListener);
    }

    public void addbtnFreshPlansActionListener(ActionListener actionListener) {
        btnFresh.addActionListener(actionListener);
    }
    public void addbtnPromeniDatumActionListener(ActionListener actionListener) {
        btnPromeniDatum.addActionListener(actionListener);
    }
}
