/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.nprog.OrdinacijaKlijent.form.planIshrane;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

import rs.ac.bg.fon.ai.nprog.OrdinacijaZajednicki.domen.PlanIshrane;

/**
 *
 * @author Iva
 */
public class FrmPlanIshranePrikaz extends javax.swing.JFrame {

	private PlanIshrane p;

	/**
	 * Creates new form FrmPlanIshranePrikaz
	 */
	public FrmPlanIshranePrikaz() {
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblPlanovi = new javax.swing.JTable();
		btnDetail = new javax.swing.JButton();
		pnlDets = new javax.swing.JPanel();
		lblDatum = new javax.swing.JLabel();
		txtDatum = new javax.swing.JTextField();
		lblCena = new javax.swing.JLabel();
		txtCena = new javax.swing.JTextField();
		txtDani = new javax.swing.JTextField();
		lblDani = new javax.swing.JLabel();
		pnlNutricionista1 = new javax.swing.JPanel();
		lblImeN = new javax.swing.JLabel();
		txtImeN = new javax.swing.JTextField();
		txtPrezimeN = new javax.swing.JTextField();
		lbPrezimeN = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblStavke = new javax.swing.JTable();
		pnlPacijent = new javax.swing.JPanel();
		lblImeP = new javax.swing.JLabel();
		txtPrezimeP = new javax.swing.JTextField();
		lblPrezimeP = new javax.swing.JLabel();
		txtImeP = new javax.swing.JTextField();
		btnBrisi = new javax.swing.JButton();
		btnIzmena = new javax.swing.JButton();
		pnlJela = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		tblJela = new javax.swing.JTable();
		lblKolicina = new javax.swing.JLabel();
		spiner = new javax.swing.JSpinner();
		btnDodajUPlan = new javax.swing.JButton();
		btnDani = new javax.swing.JButton();
		btnSacuvajIzmene = new javax.swing.JButton();
		btnDatum = new javax.swing.JButton();
		btnDelete = new javax.swing.JButton();
		cmbNutricionisti = new javax.swing.JComboBox<>();
		lblPretragaNutricionisti = new javax.swing.JLabel();
		btnPretraga = new javax.swing.JButton();
		btnUcitaj = new javax.swing.JButton();
		lblPretragaPacijenti = new javax.swing.JLabel();
		cbPacijenti = new javax.swing.JComboBox<>();
		btnResetuj = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Plan ishrane");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Planovi ishrana:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

		tblPlanovi
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblPlanovi);

		btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDetail.setText("Prikaži detalje");
		btnDetail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDetailActionPerformed(evt);
			}
		});

		pnlDets.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Detalji:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

		lblDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblDatum.setText("Datum:");

		txtDatum.setText(" ");

		lblCena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblCena.setText("Cena:");

		txtCena.setText(" ");

		txtDani.setText(" ");

		lblDani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblDani.setText("Broj dana:");

		pnlNutricionista1
				.setBorder(
						javax.swing.BorderFactory
								.createTitledBorder(
										javax.swing.BorderFactory.createCompoundBorder(null,
												javax.swing.BorderFactory
														.createLineBorder(new java.awt.Color(255, 0, 51))),
										"Nutricionista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
										javax.swing.border.TitledBorder.DEFAULT_POSITION,
										new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

		lblImeN.setText("Ime:");

		txtImeN.setText(" ");

		txtPrezimeN.setText(" ");

		lbPrezimeN.setText("Prezime:");

		javax.swing.GroupLayout pnlNutricionista1Layout = new javax.swing.GroupLayout(pnlNutricionista1);
		pnlNutricionista1.setLayout(pnlNutricionista1Layout);
		pnlNutricionista1Layout.setHorizontalGroup(pnlNutricionista1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlNutricionista1Layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(pnlNutricionista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lbPrezimeN, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblImeN, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlNutricionista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtPrezimeN, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
								.addComponent(txtImeN))
						.addContainerGap()));
		pnlNutricionista1Layout
				.setVerticalGroup(pnlNutricionista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlNutricionista1Layout.createSequentialGroup().addGroup(pnlNutricionista1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblImeN, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtImeN, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(pnlNutricionista1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lbPrezimeN, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtPrezimeN, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))));

		tblStavke
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(tblStavke);

		pnlPacijent
				.setBorder(
						javax.swing.BorderFactory
								.createTitledBorder(
										javax.swing.BorderFactory.createCompoundBorder(null,
												javax.swing.BorderFactory
														.createLineBorder(new java.awt.Color(255, 0, 51))),
										"Pacijent:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
										javax.swing.border.TitledBorder.DEFAULT_POSITION,
										new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

		lblImeP.setText("Ime:");

		txtPrezimeP.setText(" ");

		lblPrezimeP.setText("Prezime:");

		txtImeP.setText(" ");

		javax.swing.GroupLayout pnlPacijentLayout = new javax.swing.GroupLayout(pnlPacijent);
		pnlPacijent.setLayout(pnlPacijentLayout);
		pnlPacijentLayout.setHorizontalGroup(pnlPacijentLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPacijentLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblImeP, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblPrezimeP, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtImeP, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
								.addComponent(txtPrezimeP, javax.swing.GroupLayout.Alignment.TRAILING))
						.addContainerGap()));
		pnlPacijentLayout.setVerticalGroup(pnlPacijentLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPacijentLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblImeP, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtImeP, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblPrezimeP, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPrezimeP, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnBrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnBrisi.setText("Obriši stavku plana");
		btnBrisi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBrisiActionPerformed(evt);
			}
		});

		btnIzmena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnIzmena.setText("Izmeni plan");
		btnIzmena.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIzmenaActionPerformed(evt);
			}
		});

		pnlJela.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Napravi stavku plana:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

		tblJela.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane3.setViewportView(tblJela);

		lblKolicina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblKolicina.setText("Količina:");

		btnDodajUPlan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDodajUPlan.setText("Dodaj u plan");
		btnDodajUPlan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDodajUPlanActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnlJelaLayout = new javax.swing.GroupLayout(pnlJela);
		pnlJela.setLayout(pnlJelaLayout);
		pnlJelaLayout.setHorizontalGroup(pnlJelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlJelaLayout.createSequentialGroup().addGap(22, 22, 22).addGroup(pnlJelaLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlJelaLayout.createSequentialGroup().addComponent(jScrollPane3).addContainerGap())
						.addGroup(pnlJelaLayout.createSequentialGroup()
								.addComponent(lblKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnDodajUPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
										javax.swing.GroupLayout.PREFERRED_SIZE)))));
		pnlJelaLayout
				.setVerticalGroup(pnlJelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlJelaLayout.createSequentialGroup().addGap(22, 22, 22)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(pnlJelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlJelaLayout.createSequentialGroup().addGroup(pnlJelaLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 4, Short.MAX_VALUE))
										.addComponent(btnDodajUPlan, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap()));

		btnDani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDani.setForeground(new java.awt.Color(204, 204, 204));
		btnDani.setText("Promeni broj dana");
		btnDani.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDaniActionPerformed(evt);
			}
		});

		btnSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnSacuvajIzmene.setForeground(new java.awt.Color(51, 51, 255));
		btnSacuvajIzmene.setText("Sačuvaj izmene");
		btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacuvajIzmeneActionPerformed(evt);
			}
		});

		btnDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDatum.setForeground(new java.awt.Color(204, 204, 204));
		btnDatum.setText(" Promeni datum");
		btnDatum.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDatumActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnlDetsLayout = new javax.swing.GroupLayout(pnlDets);
		pnlDets.setLayout(pnlDetsLayout);
		pnlDetsLayout.setHorizontalGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlDetsLayout.createSequentialGroup().addContainerGap().addGroup(pnlDetsLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetsLayout.createSequentialGroup()
								.addGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(pnlJela, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(pnlDetsLayout.createSequentialGroup().addGroup(pnlDetsLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(pnlDetsLayout.createSequentialGroup().addGap(12, 12, 12)
														.addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE,
																61, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE,
																120, Short.MAX_VALUE)
														.addGap(39, 39, 39)
														.addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE,
																37, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE,
																101, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED))
												.addGroup(pnlDetsLayout.createSequentialGroup().addGap(6, 6, 6)
														.addComponent(lblDani, javax.swing.GroupLayout.PREFERRED_SIZE,
																61, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(pnlDetsLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(btnDatum,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(btnDani,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(txtDani))
														.addGap(134, 134, 134)))
												.addComponent(pnlNutricionista1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(pnlPacijent, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addGroup(pnlDetsLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnSacuvajIzmene,
																javax.swing.GroupLayout.PREFERRED_SIZE, 218,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btnIzmena, javax.swing.GroupLayout.PREFERRED_SIZE,
																152, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(24, 24, 24)))
								.addGap(18, 18, 18))
						.addGroup(pnlDetsLayout.createSequentialGroup().addComponent(jScrollPane2).addContainerGap())
						.addGroup(pnlDetsLayout.createSequentialGroup().addComponent(btnBrisi)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		pnlDetsLayout.setVerticalGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlDetsLayout.createSequentialGroup().addGroup(pnlDetsLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(pnlDetsLayout.createSequentialGroup().addGroup(pnlDetsLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlDetsLayout.createSequentialGroup().addContainerGap()
										.addGroup(pnlDetsLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(txtDani, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblDani, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnDani))
						.addGroup(pnlDetsLayout.createSequentialGroup().addContainerGap().addGroup(pnlDetsLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(pnlPacijent, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pnlNutricionista1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(pnlDetsLayout.createSequentialGroup()
										.addComponent(btnIzmena, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28).addComponent(btnSacuvajIzmene,
												javax.swing.GroupLayout.PREFERRED_SIZE, 39,
												javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnBrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pnlJela, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(17, Short.MAX_VALUE)));

		btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDelete.setText("Obriši plan");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});

		cmbNutricionisti.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblPretragaNutricionisti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblPretragaNutricionisti.setText("Pretraži po nutricionistima");

		btnPretraga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnPretraga.setForeground(new java.awt.Color(51, 0, 204));
		btnPretraga.setText("Pretraži");
		btnPretraga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPretragaActionPerformed(evt);
			}
		});

		btnUcitaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnUcitaj.setForeground(new java.awt.Color(51, 0, 204));
		btnUcitaj.setText("Učitaj plan ishrane");

		lblPretragaPacijenti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblPretragaPacijenti.setText("Pretraži po pacijentima");

		cbPacijenti.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnResetuj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnResetuj.setForeground(new java.awt.Color(0, 102, 102));
		btnResetuj.setText("Resetuj");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(pnlDets, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(cmbNutricionisti,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(cbPacijenti, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(lblPretragaNutricionisti,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(lblPretragaPacijenti,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE,
																120, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE,
																120, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnResetuj, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 0, Short.MAX_VALUE)))))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(3, 3, 3)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lblPretragaNutricionisti).addComponent(lblPretragaPacijenti))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(cmbNutricionisti, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(cbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnPretraga)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnUcitaj)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnResetuj))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pnlDets, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(16, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(258, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnBrisiActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnDodajUPlanActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnDaniActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnDatumActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	/*
	 * /**
	 * 
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton btnBrisi;
	private javax.swing.JButton btnDani;
	private javax.swing.JButton btnDatum;
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnDetail;
	private javax.swing.JButton btnDodajUPlan;
	private javax.swing.JButton btnIzmena;
	private javax.swing.JButton btnPretraga;
	private javax.swing.JButton btnResetuj;
	private javax.swing.JButton btnSacuvajIzmene;
	private javax.swing.JButton btnUcitaj;
	private javax.swing.JComboBox<Object> cbPacijenti;
	private javax.swing.JComboBox<Object> cmbNutricionisti;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JLabel lbPrezimeN;
	private javax.swing.JLabel lblCena;
	private javax.swing.JLabel lblDani;
	private javax.swing.JLabel lblDatum;
	private javax.swing.JLabel lblImeN;
	private javax.swing.JLabel lblImeP;
	private javax.swing.JLabel lblKolicina;
	private javax.swing.JLabel lblPretragaNutricionisti;
	private javax.swing.JLabel lblPretragaPacijenti;
	private javax.swing.JLabel lblPrezimeP;
	private javax.swing.JPanel pnlDets;
	private javax.swing.JPanel pnlJela;
	private javax.swing.JPanel pnlNutricionista1;
	private javax.swing.JPanel pnlPacijent;
	private javax.swing.JSpinner spiner;
	private javax.swing.JTable tblJela;
	private javax.swing.JTable tblPlanovi;
	private javax.swing.JTable tblStavke;
	private javax.swing.JTextField txtCena;
	private javax.swing.JTextField txtDani;
	private javax.swing.JTextField txtDatum;
	private javax.swing.JTextField txtImeN;
	private javax.swing.JTextField txtImeP;
	private javax.swing.JTextField txtPrezimeN;
	private javax.swing.JTextField txtPrezimeP;
	// End of variables declaration

	public PlanIshrane getP() {
		return p;
	}

	public JButton getBtnBrisi() {
		return btnBrisi;
	}

	public JButton getBtnDani() {
		return btnDani;
	}

	public JButton getBtnDelete() {
		return btnDelete;
	}

	public JButton getBtnDetail() {
		return btnDetail;
	}

	public JButton getBtnDodajUPlan() {
		return btnDodajUPlan;
	}

	public JButton getBtnDodajUPlan2() {
		return btnSacuvajIzmene;
	}

	public JButton getBtnIzmena() {
		return btnIzmena;
	}

	public JPanel getjPanel1() {
		return jPanel1;
	}

	public JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public JScrollPane getjScrollPane2() {
		return jScrollPane2;
	}

	public JScrollPane getjScrollPane3() {
		return jScrollPane3;
	}

	public JLabel getLbPrezimeN() {
		return lbPrezimeN;
	}

	public JLabel getLblCena() {
		return lblCena;
	}

	public JLabel getLblDani() {
		return lblDani;
	}

	public JLabel getLblDatum() {
		return lblDatum;
	}

	public JLabel getLblImeN() {
		return lblImeN;
	}

	public JLabel getLblImeP() {
		return lblImeP;
	}

	public JLabel getLblKolicina() {
		return lblKolicina;
	}

	public JLabel getLblPrezimeP() {
		return lblPrezimeP;
	}

	public JPanel getPnlDets() {
		return pnlDets;
	}

	public JPanel getPnlJela() {
		return pnlJela;
	}

	public JPanel getPnlNutricionista1() {
		return pnlNutricionista1;
	}

	public JPanel getPnlPacijent() {
		return pnlPacijent;
	}

	public JSpinner getSpiner() {
		return spiner;
	}

	public JTable getTblJela() {
		return tblJela;
	}

	public JTable getTblPlanovi() {
		return tblPlanovi;
	}

	public JTable getTblStavke() {
		return tblStavke;
	}

	public JTextField getTxtCena() {
		return txtCena;
	}

	public JTextField getTxtDani() {
		return txtDani;
	}

	public JTextField getTxtDatum() {
		return txtDatum;
	}

	public JTextField getTxtImeN() {
		return txtImeN;
	}

	public JTextField getTxtImeP() {
		return txtImeP;
	}

	public JTextField getTxtPrezimeN() {
		return txtPrezimeN;
	}

	public JTextField getTxtPrezimeP() {
		return txtPrezimeP;
	}

	public void setP(PlanIshrane p) {
		this.p = p;
	}

	public void setBtnBrisi(JButton btnBrisi) {
		this.btnBrisi = btnBrisi;
	}

	public void setBtnDani(JButton btnDani) {
		this.btnDani = btnDani;
	}

	public void setBtnDelete(JButton btnDelete) {
		this.btnDelete = btnDelete;
	}

	public void setBtnDetail(JButton btnDetail) {
		this.btnDetail = btnDetail;
	}

	public void setBtnDodajUPlan(JButton btnDodajUPlan) {
		this.btnDodajUPlan = btnDodajUPlan;
	}

	public void setBtnDodajUPlan2(JButton btnDodajUPlan2) {
		this.btnSacuvajIzmene = btnDodajUPlan2;
	}

	public void setBtnIzmena(JButton btnIzmena) {
		this.btnIzmena = btnIzmena;
	}

	public void setjPanel1(JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	public void setjScrollPane1(JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public void setjScrollPane2(JScrollPane jScrollPane2) {
		this.jScrollPane2 = jScrollPane2;
	}

	public void setjScrollPane3(JScrollPane jScrollPane3) {
		this.jScrollPane3 = jScrollPane3;
	}

	public void setLbPrezimeN(JLabel lbPrezimeN) {
		this.lbPrezimeN = lbPrezimeN;
	}

	public void setLblCena(JLabel lblCena) {
		this.lblCena = lblCena;
	}

	public void setLblDani(JLabel lblDani) {
		this.lblDani = lblDani;
	}

	public void setLblDatum(JLabel lblDatum) {
		this.lblDatum = lblDatum;
	}

	public void setLblImeN(JLabel lblImeN) {
		this.lblImeN = lblImeN;
	}

	public void setLblImeP(JLabel lblImeP) {
		this.lblImeP = lblImeP;
	}

	public void setLblKolicina(JLabel lblKolicina) {
		this.lblKolicina = lblKolicina;
	}

	public void setLblPrezimeP(JLabel lblPrezimeP) {
		this.lblPrezimeP = lblPrezimeP;
	}

	public void setPnlDets(JPanel pnlDets) {
		this.pnlDets = pnlDets;
	}

	public void setPnlJela(JPanel pnlJela) {
		this.pnlJela = pnlJela;
	}

	public void setPnlNutricionista1(JPanel pnlNutricionista1) {
		this.pnlNutricionista1 = pnlNutricionista1;
	}

	public void setPnlPacijent(JPanel pnlPacijent) {
		this.pnlPacijent = pnlPacijent;
	}

	public void setSpiner(JSpinner spiner) {
		this.spiner = spiner;
	}

	public void setTblJela(JTable tblJela) {
		this.tblJela = tblJela;
	}

	public void setTblPlanovi(JTable tblPlanovi) {
		this.tblPlanovi = tblPlanovi;
	}

	public void setTblStavke(JTable tblStavke) {
		this.tblStavke = tblStavke;
	}

	public void setTxtCena(JTextField txtCena) {
		this.txtCena = txtCena;
	}

	public void setTxtDani(JTextField txtDani) {
		this.txtDani = txtDani;
	}

	public void setTxtDatum(JTextField txtDatum) {
		this.txtDatum = txtDatum;
	}

	public void setTxtImeN(JTextField txtImeN) {
		this.txtImeN = txtImeN;
	}

	public void setTxtImeP(JTextField txtImeP) {
		this.txtImeP = txtImeP;
	}

	public void setTxtPrezimeN(JTextField txtPrezimeN) {
		this.txtPrezimeN = txtPrezimeN;
	}

	public void setTxtPrezimeP(JTextField txtPrezimeP) {
		this.txtPrezimeP = txtPrezimeP;
	}

	public JComboBox<Object> getCmbNutricionisti() {
		return cmbNutricionisti;
	}

	public void setCmbNutricionisti(JComboBox<Object> cmbNutricionisti) {
		this.cmbNutricionisti = cmbNutricionisti;
	}

	public JButton getBtnSacuvajIzmene() {
		return btnSacuvajIzmene;
	}

	public void setBtnSacuvajIzmene(JButton btnSacuvajIzmene) {
		this.btnSacuvajIzmene = btnSacuvajIzmene;
	}

	public JButton getBtnDatum() {
		return btnDatum;
	}

	public void setBtnDatum(JButton btnDatum) {
		this.btnDatum = btnDatum;
	}

	public JComboBox<Object> getCbPacijenti() {
		return cbPacijenti;
	}

	public void setCbPacijenti(JComboBox<Object> cbPacijenti) {
		this.cbPacijenti = cbPacijenti;
	}

	public void addbtnDetailActionListener(ActionListener actionListener) {
		btnDetail.addActionListener(actionListener);
	}

	public void addbtnDeleteActionListener(ActionListener actionListener) {
		btnDelete.addActionListener(actionListener);
	}

	public void addbtnIzmenaActionListener(ActionListener actionListener) {
		btnIzmena.addActionListener(actionListener);
	}

	public void addbtnDaniActionListener(ActionListener actionListener) {
		btnDani.addActionListener(actionListener);
	}

	public void addbtnDodajUPlanActionListener(ActionListener actionListener) {
		btnDodajUPlan.addActionListener(actionListener);
	}

	public void addbtnBrisiActionListener(ActionListener actionListener) {
		btnBrisi.addActionListener(actionListener);
	}

	public void addbtnSacuvajIzmeneActionListener(ActionListener actionListener) {
		btnSacuvajIzmene.addActionListener(actionListener);
	}

	public void addbtnPretragaPlanaActionListener(ActionListener actionListener) {
		btnPretraga.addActionListener(actionListener);
	}

	public void addbtnUcitajPlanActionListener(ActionListener actionListener) {
		btnUcitaj.addActionListener(actionListener);
	}

	public void addbtnPromeniDatumActionListener(ActionListener actionListener) {
		btnDatum.addActionListener(actionListener);
	}

	public void addbtnResetujActionListener(ActionListener actionListener) {
		btnResetuj.addActionListener(actionListener);
	}
}
