package rs.ac.bg.fon.ai.nprog.OrdinacijaKlijent.form.planIshrane;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

import rs.ac.bg.fon.ai.nprog.OrdinacijaZajednicki.domen.PlanIshrane;

/**
 * Forma koja umogucuje nutricionisti prikaz svih planova ishrana za pacijente
 * 
 * @author Iva Stanisic
 */
public class FrmPlanIshranePrikaz extends javax.swing.JFrame {

	/**
	 * Selektovani plan ishrane ciji se detalji gledaju
	 */
	private PlanIshrane p;

	/**
	 * Kreira novu instancu klase FrmPlanIshranePrikaz
	 * 
	 */
	public FrmPlanIshranePrikaz() {
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblPlanovi = new javax.swing.JTable();
		btnDetail = new javax.swing.JButton();
		pnlDets = new javax.swing.JPanel();
		lblDatum = new javax.swing.JLabel();
		txtDatum = new javax.swing.JTextField();
		lblCena = new javax.swing.JLabel();
		txtCena = new javax.swing.JTextField();
		txtDani = new javax.swing.JTextField();
		lblDani = new javax.swing.JLabel();
		pnlNutricionista1 = new javax.swing.JPanel();
		lblImeN = new javax.swing.JLabel();
		txtImeN = new javax.swing.JTextField();
		txtPrezimeN = new javax.swing.JTextField();
		lbPrezimeN = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblStavke = new javax.swing.JTable();
		pnlPacijent = new javax.swing.JPanel();
		lblImeP = new javax.swing.JLabel();
		txtPrezimeP = new javax.swing.JTextField();
		lblPrezimeP = new javax.swing.JLabel();
		txtImeP = new javax.swing.JTextField();
		btnBrisi = new javax.swing.JButton();
		btnIzmena = new javax.swing.JButton();
		pnlJela = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		tblJela = new javax.swing.JTable();
		lblKolicina = new javax.swing.JLabel();
		spiner = new javax.swing.JSpinner();
		btnDodajUPlan = new javax.swing.JButton();
		btnDani = new javax.swing.JButton();
		btnSacuvajIzmene = new javax.swing.JButton();
		btnDatum = new javax.swing.JButton();
		btnDelete = new javax.swing.JButton();
		cmbNutricionisti = new javax.swing.JComboBox<>();
		lblPretragaNutricionisti = new javax.swing.JLabel();
		btnPretraga = new javax.swing.JButton();
		btnUcitaj = new javax.swing.JButton();
		lblPretragaPacijenti = new javax.swing.JLabel();
		cbPacijenti = new javax.swing.JComboBox<>();
		btnResetuj = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Plan ishrane");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Planovi ishrana:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

		tblPlanovi
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblPlanovi);

		btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDetail.setText("Prikaži detalje");
		btnDetail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDetailActionPerformed(evt);
			}
		});

		pnlDets.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Detalji:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

		lblDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblDatum.setText("Datum:");

		txtDatum.setText(" ");

		lblCena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblCena.setText("Cena:");

		txtCena.setText(" ");

		txtDani.setText(" ");

		lblDani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblDani.setText("Broj dana:");

		pnlNutricionista1
				.setBorder(
						javax.swing.BorderFactory
								.createTitledBorder(
										javax.swing.BorderFactory.createCompoundBorder(null,
												javax.swing.BorderFactory
														.createLineBorder(new java.awt.Color(255, 0, 51))),
										"Nutricionista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
										javax.swing.border.TitledBorder.DEFAULT_POSITION,
										new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

		lblImeN.setText("Ime:");

		txtImeN.setText(" ");

		txtPrezimeN.setText(" ");

		lbPrezimeN.setText("Prezime:");

		javax.swing.GroupLayout pnlNutricionista1Layout = new javax.swing.GroupLayout(pnlNutricionista1);
		pnlNutricionista1.setLayout(pnlNutricionista1Layout);
		pnlNutricionista1Layout.setHorizontalGroup(pnlNutricionista1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlNutricionista1Layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(pnlNutricionista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lbPrezimeN, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblImeN, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlNutricionista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtPrezimeN, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
								.addComponent(txtImeN))
						.addContainerGap()));
		pnlNutricionista1Layout
				.setVerticalGroup(pnlNutricionista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlNutricionista1Layout.createSequentialGroup().addGroup(pnlNutricionista1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblImeN, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtImeN, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(pnlNutricionista1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lbPrezimeN, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtPrezimeN, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))));

		tblStavke
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(tblStavke);

		pnlPacijent
				.setBorder(
						javax.swing.BorderFactory
								.createTitledBorder(
										javax.swing.BorderFactory.createCompoundBorder(null,
												javax.swing.BorderFactory
														.createLineBorder(new java.awt.Color(255, 0, 51))),
										"Pacijent:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
										javax.swing.border.TitledBorder.DEFAULT_POSITION,
										new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

		lblImeP.setText("Ime:");

		txtPrezimeP.setText(" ");

		lblPrezimeP.setText("Prezime:");

		txtImeP.setText(" ");

		javax.swing.GroupLayout pnlPacijentLayout = new javax.swing.GroupLayout(pnlPacijent);
		pnlPacijent.setLayout(pnlPacijentLayout);
		pnlPacijentLayout.setHorizontalGroup(pnlPacijentLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPacijentLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblImeP, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblPrezimeP, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtImeP, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
								.addComponent(txtPrezimeP, javax.swing.GroupLayout.Alignment.TRAILING))
						.addContainerGap()));
		pnlPacijentLayout.setVerticalGroup(pnlPacijentLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPacijentLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblImeP, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtImeP, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblPrezimeP, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPrezimeP, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnBrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnBrisi.setText("Obriši stavku plana");
		btnBrisi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBrisiActionPerformed(evt);
			}
		});

		btnIzmena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnIzmena.setText("Izmeni plan");
		btnIzmena.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIzmenaActionPerformed(evt);
			}
		});

		pnlJela.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray,
						java.awt.Color.darkGray, null, null),
				"Napravi stavku plana:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

		tblJela.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane3.setViewportView(tblJela);

		lblKolicina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblKolicina.setText("Količina:");

		btnDodajUPlan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDodajUPlan.setText("Dodaj u plan");
		btnDodajUPlan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDodajUPlanActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnlJelaLayout = new javax.swing.GroupLayout(pnlJela);
		pnlJela.setLayout(pnlJelaLayout);
		pnlJelaLayout.setHorizontalGroup(pnlJelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlJelaLayout.createSequentialGroup().addGap(22, 22, 22).addGroup(pnlJelaLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlJelaLayout.createSequentialGroup().addComponent(jScrollPane3).addContainerGap())
						.addGroup(pnlJelaLayout.createSequentialGroup()
								.addComponent(lblKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnDodajUPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
										javax.swing.GroupLayout.PREFERRED_SIZE)))));
		pnlJelaLayout
				.setVerticalGroup(pnlJelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlJelaLayout.createSequentialGroup().addGap(22, 22, 22)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(pnlJelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlJelaLayout.createSequentialGroup().addGroup(pnlJelaLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 4, Short.MAX_VALUE))
										.addComponent(btnDodajUPlan, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap()));

		btnDani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDani.setForeground(new java.awt.Color(204, 204, 204));
		btnDani.setText("Promeni broj dana");
		btnDani.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDaniActionPerformed(evt);
			}
		});

		btnSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnSacuvajIzmene.setForeground(new java.awt.Color(51, 51, 255));
		btnSacuvajIzmene.setText("Sačuvaj izmene");
		btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacuvajIzmeneActionPerformed(evt);
			}
		});

		btnDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDatum.setForeground(new java.awt.Color(204, 204, 204));
		btnDatum.setText(" Promeni datum");
		btnDatum.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDatumActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnlDetsLayout = new javax.swing.GroupLayout(pnlDets);
		pnlDets.setLayout(pnlDetsLayout);
		pnlDetsLayout.setHorizontalGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlDetsLayout.createSequentialGroup().addContainerGap().addGroup(pnlDetsLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetsLayout.createSequentialGroup()
								.addGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(pnlJela, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(pnlDetsLayout.createSequentialGroup().addGroup(pnlDetsLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(pnlDetsLayout.createSequentialGroup().addGap(12, 12, 12)
														.addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE,
																61, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE,
																120, Short.MAX_VALUE)
														.addGap(39, 39, 39)
														.addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE,
																37, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE,
																101, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED))
												.addGroup(pnlDetsLayout.createSequentialGroup().addGap(6, 6, 6)
														.addComponent(lblDani, javax.swing.GroupLayout.PREFERRED_SIZE,
																61, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(pnlDetsLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(btnDatum,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(btnDani,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(txtDani))
														.addGap(134, 134, 134)))
												.addComponent(pnlNutricionista1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(pnlPacijent, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addGroup(pnlDetsLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnSacuvajIzmene,
																javax.swing.GroupLayout.PREFERRED_SIZE, 218,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btnIzmena, javax.swing.GroupLayout.PREFERRED_SIZE,
																152, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(24, 24, 24)))
								.addGap(18, 18, 18))
						.addGroup(pnlDetsLayout.createSequentialGroup().addComponent(jScrollPane2).addContainerGap())
						.addGroup(pnlDetsLayout.createSequentialGroup().addComponent(btnBrisi)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		pnlDetsLayout.setVerticalGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlDetsLayout.createSequentialGroup().addGroup(pnlDetsLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(pnlDetsLayout.createSequentialGroup().addGroup(pnlDetsLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlDetsLayout.createSequentialGroup().addContainerGap()
										.addGroup(pnlDetsLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(pnlDetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(txtDani, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblDani, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnDani))
						.addGroup(pnlDetsLayout.createSequentialGroup().addContainerGap().addGroup(pnlDetsLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(pnlPacijent, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pnlNutricionista1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(pnlDetsLayout.createSequentialGroup()
										.addComponent(btnIzmena, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28).addComponent(btnSacuvajIzmene,
												javax.swing.GroupLayout.PREFERRED_SIZE, 39,
												javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnBrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pnlJela, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(17, Short.MAX_VALUE)));

		btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnDelete.setText("Obriši plan");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});

		cmbNutricionisti.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblPretragaNutricionisti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblPretragaNutricionisti.setText("Pretraži po nutricionistima");

		btnPretraga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnPretraga.setForeground(new java.awt.Color(51, 0, 204));
		btnPretraga.setText("Pretraži");
		btnPretraga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPretragaActionPerformed(evt);
			}
		});

		btnUcitaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnUcitaj.setForeground(new java.awt.Color(51, 0, 204));
		btnUcitaj.setText("Učitaj plan ishrane");

		lblPretragaPacijenti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblPretragaPacijenti.setText("Pretraži po pacijentima");

		cbPacijenti.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnResetuj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnResetuj.setForeground(new java.awt.Color(0, 102, 102));
		btnResetuj.setText("Resetuj");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(pnlDets, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(cmbNutricionisti,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(cbPacijenti, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(lblPretragaNutricionisti,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(lblPretragaPacijenti,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE,
																120, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE,
																120, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnResetuj, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 0, Short.MAX_VALUE)))))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(3, 3, 3)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lblPretragaNutricionisti).addComponent(lblPretragaPacijenti))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(cmbNutricionisti, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(cbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnPretraga)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnUcitaj)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnResetuj))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pnlDets, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(16, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(258, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnBrisiActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnDodajUPlanActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnDaniActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnDatumActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	/*
	 * /**
	 * 
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	/**
	 * Referenca na JButton objekat koji predstavlja dugme za brisanje.
	 */
	private javax.swing.JButton btnBrisi;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za prikazivanje dana.
	 */
	private javax.swing.JButton btnDani;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za odabir datuma.
	 */
	private javax.swing.JButton btnDatum;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za brisanje.
	 */
	private javax.swing.JButton btnDelete;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za prikazivanje detalja.
	 */
	private javax.swing.JButton btnDetail;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za dodavanje u plan.
	 */
	private javax.swing.JButton btnDodajUPlan;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za izmenu.
	 */
	private javax.swing.JButton btnIzmena;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za pretragu.
	 */
	private javax.swing.JButton btnPretraga;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za resetovanje.
	 */
	private javax.swing.JButton btnResetuj;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za čuvanje izmena.
	 */
	private javax.swing.JButton btnSacuvajIzmene;

	/**
	 * Referenca na JButton objekat koji predstavlja dugme za učitavanje.
	 */
	private javax.swing.JButton btnUcitaj;

	/**
	 * Referenca na JComboBox objekat koji predstavlja izbor pacijenata.
	 */
	private javax.swing.JComboBox<Object> cbPacijenti;

	/**
	 * Referenca na JComboBox objekat koji predstavlja izbor nutricionista.
	 */
	private javax.swing.JComboBox<Object> cmbNutricionisti;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel.
	 */
	private javax.swing.JPanel jPanel1;

	/**
	 * Referenca na JScrollPane objekat koji omogućava klizanje za prvi JScrollPane.
	 */
	private javax.swing.JScrollPane jScrollPane1;

	/**
	 * Referenca na JScrollPane objekat koji omogućava klizanje za drugi JScrollPane.
	 */
	private javax.swing.JScrollPane jScrollPane2;
	/**
	 * Referenca na JScrollPane objekat koji omogućava klizanje za treci JScrollPane.
	 */
	private javax.swing.JScrollPane jScrollPane3;

	/**
	 * Referenca na JScrollPane objekat koji omogućava klizanje za treći JScrollPane.
	 */
	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za prezime nutricioniste.
	 */
	private javax.swing.JLabel lbPrezimeN;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za cenu.
	 */
	private javax.swing.JLabel lblCena;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za dane.
	 */
	private javax.swing.JLabel lblDani;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za datum.
	 */
	private javax.swing.JLabel lblDatum;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za ime nutricioniste.
	 */
	private javax.swing.JLabel lblImeN;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za ime pacijenta.
	 */
	private javax.swing.JLabel lblImeP;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za količinu.
	 */
	private javax.swing.JLabel lblKolicina;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za pretragu nutricionista.
	 */
	private javax.swing.JLabel lblPretragaNutricionisti;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za pretragu pacijenata.
	 */
	private javax.swing.JLabel lblPretragaPacijenti;

	/**
	 * Referenca na JLabel objekat koji predstavlja oznaku za prezime pacijenta.
	 */
	private javax.swing.JLabel lblPrezimeP;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel detalja.
	 */
	private javax.swing.JPanel pnlDets;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel jela.
	 */
	private javax.swing.JPanel pnlJela;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel nutricionista.
	 */
	private javax.swing.JPanel pnlNutricionista1;

	/**
	 * Referenca na JPanel objekat koji predstavlja panel pacijenta.
	 */
	private javax.swing.JPanel pnlPacijent;

	/**
	 * Referenca na JSpinner objekat koji predstavlja spinner za unos broja.
	 */
	private javax.swing.JSpinner spiner;

	/**
	 * Referenca na JTable objekat koji predstavlja tabelu jela.
	 */
	private javax.swing.JTable tblJela;

	/**
	 * Referenca na JTable objekat koji predstavlja tabelu planova.
	 */
	private javax.swing.JTable tblPlanovi;

	/**
	 * Referenca na JTable objekat koji predstavlja tabelu stavki.
	 */
	private javax.swing.JTable tblStavke;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za cenu.
	 */
	private javax.swing.JTextField txtCena;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za dane.
	 */
	private javax.swing.JTextField txtDani;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za datum.
	 */
	private javax.swing.JTextField txtDatum;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za ime nutricioniste.
	 */
	private javax.swing.JTextField txtImeN;
	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za ime pacijenta.
	 */
	private javax.swing.JTextField txtImeP;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za prezime nutricioniste.
	 */
	private javax.swing.JTextField txtPrezimeN;

	/**
	 * Referenca na JTextField objekat koji predstavlja tekstualno polje za prezime pacijenta.
	 */
	private javax.swing.JTextField txtPrezimeP;
	// End of variables declaration

	/**
	 * Vraca selektovani plan
	 * 
	 * @return selektovani plan ishrane
	 */
	public PlanIshrane getP() {
		return p;
	}

	/**
	 * Vraca JButton btnBrisi
	 *
	 * @return JButton btnBrisi
	 */
	public JButton getBtnBrisi() {
		return btnBrisi;
	}

	/**
	 * Vraca JButton btnDani
	 *
	 * @return JButton btnDani
	 */
	public JButton getBtnDani() {
		return btnDani;
	}

	/**
	 * Vraca JButton btnDelete
	 *
	 * @return JButton btnDelete
	 */
	public JButton getBtnDelete() {
		return btnDelete;
	}

	/**
	 * Vraca JButton btnDetail
	 *
	 * @return JButton btnDetail
	 */
	public JButton getBtnDetail() {
		return btnDetail;
	}

	/**
	 * Vraca JButton btnDodajUPlan
	 *
	 * @return JButton btnDodajUPlan
	 */
	public JButton getBtnDodajUPlan() {
		return btnDodajUPlan;
	}

	/**
	 * Vraca JButton btnSacuvajIzmene
	 *
	 * @return JButton btnSacuvajIzmene
	 */
	public JButton getBtnDodajUPlan2() {
		return btnSacuvajIzmene;
	}

	/**
	 * Vraca JButton btnIzmena
	 *
	 * @return JButton btnIzmena
	 */
	public JButton getBtnIzmena() {
		return btnIzmena;
	}

	/**
	 * Vraca JPanel JPanel na kojem se prikazuje cmb sa nutricionistima i tabela sa
	 * planovima ishrana
	 *
	 * @return JPanel jPanel1
	 */
	public JPanel getjPanel1() {
		return jPanel1;
	}

	/**
	 * Vraca JScrollPane jScrollPane1 na kojem se nalazi panel jPanel1
	 *
	 * @return JScrollPane jScrollPane1
	 */
	public JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	/**
	 * Vraca JScrollPane jScrollPane2 na kojem se nalazi panel jPanel2
	 *
	 * @return JScrollPane jScrollPane2
	 */
	public JScrollPane getjScrollPane2() {
		return jScrollPane2;
	}

	/**
	 * Vraca JScrollPane jScrollPane3
	 * 
	 * @return JScrollPane jScrollPane3
	 */
	public JScrollPane getjScrollPane3() {
		return jScrollPane3;
	}

	/**
	 * Vraca JLabel lbPrezimeN sa prezimenom nutricioniste
	 * 
	 * @return lbPrezimeN prezime nutricioniste
	 */
	public JLabel getLbPrezimeN() {
		return lbPrezimeN;
	}

	/**
	 * Vraca JLabel lblCena sa cenom plana
	 * 
	 * @return lblCena cena plana
	 */
	public JLabel getLblCena() {
		return lblCena;
	}

	/**
	 * Vraca JLabel lblDani sa brojem dana plana
	 * 
	 * @return lblDani broj dana plana
	 */
	public JLabel getLblDani() {
		return lblDani;
	}

	/**
	 * Vraca JLabel lblDatum
	 *
	 * @return JLabel lblDatum
	 */
	public JLabel getLblDatum() {
		return lblDatum;
	}

	/**
	 * Vraca JLabel lblImeN
	 *
	 * @return JLabel lblImeN
	 */
	public JLabel getLblImeN() {
		return lblImeN;
	}

	/**
	 * Vraca JLabel lblImeP
	 *
	 * @return JLabel lblImeP
	 */
	public JLabel getLblImeP() {
		return lblImeP;
	}

	/**
	 * Vraca JLabel lblKolicina
	 *
	 * @return JLabel lblKolicina
	 */
	public JLabel getLblKolicina() {
		return lblKolicina;
	}

	/**
	 * Vraca JLabel lblPrezimeP
	 *
	 * @return JLabel lblPrezimeP
	 */
	public JLabel getLblPrezimeP() {
		return lblPrezimeP;
	}

	/**
	 * Vraca JPanel pnlDets
	 *
	 * @return JPanel pnlDets
	 */
	public JPanel getPnlDets() {
		return pnlDets;
	}

	/**
	 * Vraca JPanel pnlJela sa jelima
	 *
	 * @return JPanel pnlJela
	 */
	public JPanel getPnlJela() {
		return pnlJela;
	}

	/**
	 * Vraca JPanel pnlNutricionista1 sa podacima o nutricionisti
	 *
	 * @return JPanel pnlNutricionista1
	 */
	public JPanel getPnlNutricionista1() {
		return pnlNutricionista1;
	}

	/**
	 * Vraca JPanel pnlPacijent sa podacima o pacijentu
	 *
	 * @return JPanel pnlPacijent
	 */
	public JPanel getPnlPacijent() {
		return pnlPacijent;
	}

	/**
	 * Vraca JSpinner spiner
	 *
	 * @return JSpinner spiner
	 */
	public JSpinner getSpiner() {
		return spiner;
	}

	/**
	 * Vraca JTable tblJela za prikaz jela na sistemu
	 *
	 * @return JTable tblJela
	 */
	public JTable getTblJela() {
		return tblJela;
	}

	/**
	 * Vraca JTable tblPlanovi za prikaz planova ishrana na sistemu
	 *
	 * @return JTable tblPlanovi
	 */
	public JTable getTblPlanovi() {
		return tblPlanovi;
	}

	/**
	 * Vraca JTable tblStavke za prikaz stavki planova ishrana na sistemu
	 *
	 * @return JTable tblStavke
	 */
	public JTable getTblStavke() {
		return tblStavke;
	}

	/**
	 * Vraca JTextField txtCena
	 *
	 * @return JTextField txtCena
	 */
	public JTextField getTxtCena() {
		return txtCena;
	}

	/**
	 * Vraca JTextField txtDay za unos broja trajanja plana ishrane
	 *
	 * @return JTextField txtDay
	 */
	public JTextField getTxtDani() {
		return txtDani;
	}

	/**
	 * Vraca JTextField tblStavke za prikaz stavki plana ishrane
	 *
	 * @return JTextField tblStavke
	 */
	public JTextField getTxtDatum() {
		return txtDatum;
	}

	/**
	 * Vraca JTextField txtImeN za prikaz imena nutricioniste za plan ishrane
	 *
	 * @return JTextField txtImeN
	 */
	public JTextField getTxtImeN() {
		return txtImeN;
	}

	/**
	 * Vraca JTextField txtImeP za prikaz imena pacijenta za plan ishrane
	 *
	 * @return JTextField txtImeP
	 */
	public JTextField getTxtImeP() {
		return txtImeP;
	}

	/**
	 * Vraca JTextField txtPrezimeN za prikaz prezimena nutricioniste za plan
	 * ishrane
	 *
	 * @return JTextField txtPrezimeN
	 */
	public JTextField getTxtPrezimeN() {
		return txtPrezimeN;
	}

	/**
	 * Vraca JTextField txtPrezimeP za prikaz prezimena pacijenta za plan ishrane
	 *
	 * @return JTextField txtPrezimeP
	 */
	public JTextField getTxtPrezimeP() {
		return txtPrezimeP;
	}

	/**
	 * Postavlja plan ishrane na panel sa detaljima plana
	 * 
	 * @param p plan ishrane koji je izabran za prikaz detalja
	 */
	public void setP(PlanIshrane p) {
		this.p = p;
	}

	/**
	 * Postavlja JButton btnBrisi
	 *
	 * @param btnBrisi JButton dugme za brisanje plana
	 */
	public void setBtnBrisi(JButton btnBrisi) {
		this.btnBrisi = btnBrisi;
	}

	/**
	 * Postavlja JButton btnDani
	 *
	 * @param btnDani JButton dugme za broj dana plana
	 */
	public void setBtnDani(JButton btnDani) {
		this.btnDani = btnDani;
	}

	/**
	 * Postavlja JButton btnDelete
	 *
	 * @param btnDelete JButton dugme za brisanje stavki plana
	 */
	public void setBtnDelete(JButton btnDelete) {
		this.btnDelete = btnDelete;
	}

	/**
	 * Postavlja JButton btnDetail
	 *
	 * @param btnDetail JButton dugme za prikaz detalja plana
	 */
	public void setBtnDetail(JButton btnDetail) {
		this.btnDetail = btnDetail;
	}

	/**
	 * Postavlja JButton btnDodajUPlan
	 *
	 * @param btnDodajUPlan JButton dugme za dodavanje stavki u plan
	 */
	public void setBtnDodajUPlan(JButton btnDodajUPlan) {
		this.btnDodajUPlan = btnDodajUPlan;
	}

	/**
	 * Postavlja JButton btnDodajUPlan2
	 *
	 * @param btnDodajUPlan2 JButton dugme za dodavanje stavki u plan
	 */
	public void setBtnDodajUPlan2(JButton btnDodajUPlan2) {
		this.btnSacuvajIzmene = btnDodajUPlan2;
	}

	/**
	 * Postavlja JButton btnIzmena
	 *
	 * @param btnIzmena JButton dugme za izmenu plana
	 */
	public void setBtnIzmena(JButton btnIzmena) {
		this.btnIzmena = btnIzmena;
	}

	/**
	 * Postavlja JPanel jPanel1 na formu
	 *
	 * @param jPanel1 JPanel
	 */
	public void setjPanel1(JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	/**
	 * Postavlja JScrollPane jScrollPane1 na formu
	 *
	 * @param jScrollPane1 JScrollPane
	 */
	public void setjScrollPane1(JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	/**
	 * Postavlja JScrollPane jScrollPane2 na formu
	 *
	 * @param jScrollPane2 JScrollPane
	 */
	public void setjScrollPane2(JScrollPane jScrollPane2) {
		this.jScrollPane2 = jScrollPane2;
	}

	/**
	 * Postavlja JScrollPane jScrollPane3 na formu
	 *
	 * @param jScrollPane3 JScrollPane
	 */
	public void setjScrollPane3(JScrollPane jScrollPane3) {
		this.jScrollPane3 = jScrollPane3;
	}

	/**
	 * Postavlja JLabel lbPrezimeN
	 * 
	 * @param lbPrezimeN labela koja se postavlja
	 */
	public void setLbPrezimeN(JLabel lbPrezimeN) {
		this.lbPrezimeN = lbPrezimeN;
	}

	/**
	 * Postavlja JLabel lblCena
	 * 
	 * @param lblCena labela koja se postavlja
	 */
	public void setLblCena(JLabel lblCena) {
		this.lblCena = lblCena;
	}

	/**
	 * Postavlja JLabel lblDani
	 * 
	 * @param lblDani labela koja se postavlja
	 */
	public void setLblDani(JLabel lblDani) {
		this.lblDani = lblDani;
	}

	/**
	 * Postavlja JLabel lblDatum
	 * 
	 * @param lblDatum labela koja se postavlja
	 */
	public void setLblDatum(JLabel lblDatum) {
		this.lblDatum = lblDatum;
	}

	/**
	 * Postavlja JLabel lblImeN
	 * 
	 * @param lblImeN labela koja se postavlja
	 */
	public void setLblImeN(JLabel lblImeN) {
		this.lblImeN = lblImeN;
	}

	/**
	 * Postavlja JLabel lblImeP
	 * 
	 * @param lblImeP labela koja se postavlja
	 */
	public void setLblImeP(JLabel lblImeP) {
		this.lblImeP = lblImeP;
	}

	/**
	 * Postavlja JLabel lblKolicina
	 * 
	 * @param lblKolicina labela koja se postavlja
	 */
	public void setLblKolicina(JLabel lblKolicina) {
		this.lblKolicina = lblKolicina;
	}

	/**
	 * Postavlja JLabel lblPrezimeP
	 * 
	 * @param lblPrezimeP labela koja se postavlja
	 */
	public void setLblPrezimeP(JLabel lblPrezimeP) {
		this.lblPrezimeP = lblPrezimeP;
	}

	/**
	 * Postavlja JPanel pnlDets
	 * 
	 * @param pnlDets panel koji se postavlja
	 */
	public void setPnlDets(JPanel pnlDets) {
		this.pnlDets = pnlDets;
	}

	/**
	 * Postavlja JPanel pnlJela
	 * 
	 * @param pnlJela panel koji se postavlja
	 */
	public void setPnlJela(JPanel pnlJela) {
		this.pnlJela = pnlJela;
	}

	/**
	 * Postavlja JPanel pnlNutricionista1
	 * 
	 * @param pnlNutricionista1 panel koji se postavlja
	 */
	public void setPnlNutricionista1(JPanel pnlNutricionista1) {
		this.pnlNutricionista1 = pnlNutricionista1;
	}

	/**
	 * Postavlja JPanel pnlPacijent
	 * 
	 * @param pnlPacijent panel koji se postavlja
	 */
	public void setPnlPacijent(JPanel pnlPacijent) {
		this.pnlPacijent = pnlPacijent;
	}

	/**
	 * Postavlja spiner za kolicinu
	 * 
	 * @param spiner za kolicinu
	 */
	public void setSpiner(JSpinner spiner) {
		this.spiner = spiner;
	}

	/**
	 * Postavlja JTable tblJela za prikaz jela
	 * 
	 * @param tblJela tabela koja se postavlja
	 */
	public void setTblJela(JTable tblJela) {
		this.tblJela = tblJela;
	}

	/**
	 * Postavlja JTable tblPlanovi za prikaz planova
	 * 
	 * @param tblPlanovi tabela koja se postavlja
	 */
	public void setTblPlanovi(JTable tblPlanovi) {
		this.tblPlanovi = tblPlanovi;
	}

	/**
	 * Postavlja JTable tblStavke za prikaz stavki plana
	 * 
	 * @param tblStavke tabela koja se postavlja
	 */
	public void setTblStavke(JTable tblStavke) {
		this.tblStavke = tblStavke;
	}

	/**
	 * Postavlja JTextField txtCena za prikaz cene plana ishrana
	 * 
	 * @param txtCena polje koja se postavlja
	 */
	public void setTxtCena(JTextField txtCena) {
		this.txtCena = txtCena;
	}

	/**
	 * Postavlja JTextField txtDani za prikaz broja dana plana ishrana
	 * 
	 * @param txtDani polje koja se postavlja
	 */
	public void setTxtDani(JTextField txtDani) {
		this.txtDani = txtDani;
	}

	/**
	 * Postavlja JTextField txtDatum za prikaz datuma plana ishrana
	 * 
	 * @param txtDatum polje koja se postavlja
	 */
	public void setTxtDatum(JTextField txtDatum) {
		this.txtDatum = txtDatum;
	}

	/**
	 * Postavlja JTextField txtImeN za prikaz imena nutricioniste plana ishrana
	 * 
	 * @param txtImeN polje koja se postavlja
	 */
	public void setTxtImeN(JTextField txtImeN) {
		this.txtImeN = txtImeN;
	}

	/**
	 * Postavlja JTextField txtImeP za prikaz imena pacijenta plana ishrana
	 * 
	 * @param txtImeP polje koja se postavlja
	 */
	public void setTxtImeP(JTextField txtImeP) {
		this.txtImeP = txtImeP;
	}

	/**
	 * Postavlja JTextField txtPrezimeN za prikaz prezimena nutricioniste plana
	 * ishrana
	 * 
	 * @param txtPrezimeN polje koja se postavlja
	 */
	public void setTxtPrezimeN(JTextField txtPrezimeN) {
		this.txtPrezimeN = txtPrezimeN;
	}

	/**
	 * Postavlja JTextField txtPrezimeP za prikaz prezimena pacijenta plana ishrana
	 * 
	 * @param txtPrezimeP polje koja se postavlja
	 */
	public void setTxtPrezimeP(JTextField txtPrezimeP) {
		this.txtPrezimeP = txtPrezimeP;
	}

	/**
	 * Vraca JComboBox sa nutricionistima
	 *
	 * @return cmbNutricionisti combobox sa nutricionistima
	 */
	public JComboBox<Object> getCmbNutricionisti() {
		return cmbNutricionisti;
	}

	/**
	 * Postavlja JComboBox sa nutricionistima
	 * 
	 * @param cmbNutricionisti nutricionisti
	 */
	public void setCmbNutricionisti(JComboBox<Object> cmbNutricionisti) {
		this.cmbNutricionisti = cmbNutricionisti;
	}

	/**
	 * Vraca JButton btnSacuvajIzmene
	 *
	 * @return JButton btnSacuvajIzmene
	 */
	public JButton getBtnSacuvajIzmene() {
		return btnSacuvajIzmene;
	}

	/**
	 * Postavlja JButton btnSacuvajIzmene
	 *
	 * @param btnSacuvajIzmene JButton btnSacuvajIzmene
	 */
	public void setBtnSacuvajIzmene(JButton btnSacuvajIzmene) {
		this.btnSacuvajIzmene = btnSacuvajIzmene;
	}
	/**
	 * Vraca JButton btnSacuvajIzmene
	 *
	 * @return JButton btnDatum
	 */
	public JButton getBtnDatum() {
		return btnDatum;
	}
	/**
	 * Postavlja JButton btnDatum
	 *
	 * @param btnDatum JButton 
	 */
	public void setBtnDatum(JButton btnDatum) {
		this.btnDatum = btnDatum;
	}
	/**
	 * Vraca JComboBox sa pacijentima
	 * 
	 * @return cbPacijenti pacijentima
	 */
	public JComboBox<Object> getCbPacijenti() {
		return cbPacijenti;
	}
	/**
	 * Postavlja JComboBox sa pacijentima
	 * 
	 * @param cbPacijenti pacijenti
	 */
	public void setCbPacijenti(JComboBox<Object> cbPacijenti) {
		this.cbPacijenti = cbPacijenti;
	}
	/**
	 * Dodaje ActionListener na dugme btnDetail
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnDetailActionListener(ActionListener actionListener) {
		btnDetail.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnDelete
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnDeleteActionListener(ActionListener actionListener) {
		btnDelete.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnIzmena
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnIzmenaActionListener(ActionListener actionListener) {
		btnIzmena.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnDani
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnDaniActionListener(ActionListener actionListener) {
		btnDani.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnDodajUPlan
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnDodajUPlanActionListener(ActionListener actionListener) {
		btnDodajUPlan.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnBrisi
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnBrisiActionListener(ActionListener actionListener) {
		btnBrisi.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnSacuvajIzmene
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnSacuvajIzmeneActionListener(ActionListener actionListener) {
		btnSacuvajIzmene.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnPretraga
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnPretragaPlanaActionListener(ActionListener actionListener) {
		btnPretraga.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnUcitaj
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnUcitajPlanActionListener(ActionListener actionListener) {
		btnUcitaj.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnDatum
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnPromeniDatumActionListener(ActionListener actionListener) {
		btnDatum.addActionListener(actionListener);
	}
	/**
	 * Dodaje ActionListener na dugme btnResetuj
	 *
	 * @param actionListener ActionListener koji treba dodati
	 */
	public void addbtnResetujActionListener(ActionListener actionListener) {
		btnResetuj.addActionListener(actionListener);
	}
}
