package rs.ac.bg.fon.ai.nprog.OrdinacijaZajednicki.operacije;

public enum Operacije {
	PRIJAVI_SE,
    VRATI_NUTRICIONISTE,
    ODJAVI_SE,
    SVI_PACIJENTI,
    KREIRAJ_PACIJENTA,
    OBRISI_PACIJENTA,
    IZMENI_PACIJENTA,
    NADJI_PACIJENTE,
    UCITAJ_PACIJENTA,
    VRATI_TIP_JELA,
    VRATI_KUVARE,
    KREIRAJ_JELO,
    VRATI_JELA,
    NADJI_JELA,
    KREIRAJ_PLAN_ISHRANE,
    VRATI_PLANOVE,
    NADJI_PLAN_ISHRANE,
    UCITAJ_PLAN_ISHRANE,
    OBRISI_PLAN_ISHRANE,
    IZMENI_PLAN_ISHRANE,
}
